### ISSUE TITLE
Sketch to big

### ISSUE THREAD

**Issue by bloop16** [dirkbeer/Helium_MakerfabsSoilMoistureSensorV3#3]
Hy,
Im trying to use your sketch on a view ordered SoilMiostureSensors V3.
I also ordered the cp2104-usb-to-serial-converter you recommended.

I always get the error that the sketch seams to be to big. Have installed exactly the library Versions you have recommended and believe i choose the wright board. Didn`t really change something to the code only the EUIs.

Would be nice when you could help me!

![image](https://github.com/dirkbeer/Helium_MakerfabsSoilMoistureSensorV3/assets/84281085/353f7028-e411-4228-ba8e-197fd4e1fbcf)

Thanks a lot
Martin

**Comment by bloop16** [comment]
With MCCI LoRaWAN LMIC library, Version: 4.1.1 it worked to flash

**Comment by dirkbeer** [comment]
Sorry about the delay in responding. Glad you got it working! Thank you for posting your solution.

Dirk

Sent from ProtonMail mobile

-------- Original Message --------
